[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = mysql+mysqlclient://user:pass@localhost:3306/ai_chat

[post_write_hooks]
hooks = black
black.type = console_scripts
black.entrypoint = black
